[2017-05-11 18:10:02] 连接数据库错误，原因2003: Can't connect to MySQL server on 'ip' (60)
Traceback (most recent call last):
  File "spider.py", line 187, in <module>
    spider.main()       
  File "spider.py", line 161, in main
    page = open('page.txt', 'r')
IOError: [Errno 2] No such file or directory: 'page.txt'
[2017-05-11 18:26:41] 连接数据库错误，原因2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Traceback (most recent call last):
  File "spider.py", line 187, in <module>
    spider.main()       
  File "spider.py", line 161, in main
    page = open('page.txt', 'r')
IOError: [Errno 2] No such file or directory: 'page.txt'
[2017-05-11 18:28:25] 连接数据库错误，原因2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Traceback (most recent call last):
  File "spider.py", line 187, in <module>
    spider.main()       
  File "spider.py", line 163, in main
    start_page = int(content.strip()) - 1
ValueError: invalid literal for int() with base 10: ''
